### ISSUE TITLE
Offline compile for Windows still pending

### ISSUE THREAD

**Issue by imtekalex** [imtekalex/emes_template#6]
Currently, after Installing TexLive for Windows and the LaTeX Workshop extension for Visual Studio Code, no .pdf file can be generated. The error is likely caused by a wrong or missing configuration file for Windows.

```
Initial Win CP for (console input, console output, system): (CP850, CP850, CP1252)
I changed them all to CP1252
Rc files read:
  NONE
Latexmk: This is Latexmk, John Collins, 24 Dec. 2023. Version 4.82.
No existing .aux file, so I'll make a simple one, and require run of *latex.
Latexmk: applying rule 'pdflatex'...
Rule 'pdflatex':  Reasons for rerun
Category 'other':
  Rerun of 'pdflatex' forced or previously required

------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -synctex=1 -interaction=nonstopmode -file-line-error -recorder  "c:/Users/PC/Downloads/emes_template-main/emes_template-main/settings+/docclass.tex"'
------------
This is pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(c:/Users/PC/Downloads/emes_template-main/emes_template-main/settings+/docclass.tex
LaTeX2e <2023-11-01>
L3 programming layer <2024-01-04>
(c:/texlive/2023/texmf-dist/tex/latex/koma-script/scrbook.cls
Document Class: scrbook 2023/07/07 v3.41 KOMA-Script document class (book)
(c:/texlive/2023/texmf-dist/tex/latex/koma-script/scrkbase.sty (c:/texlive/2023/texmf-dist/tex/latex/koma-script/scrbase.sty (c:/texlive/2023/texmf-dist/tex/latex/koma-script/scrlfile.sty (c:/texlive/2023/texmf-dist/tex/latex/koma-script/scrlfile-hook.sty (c:/texlive/2023/texmf-dist/tex/latex/koma-script/scrlogo.sty))) (c:/texlive/2023/texmf-dist/tex/latex/graphics/keyval.sty))) (c:/texlive/2023/texmf-dist/tex/latex/koma-script/tocbasic.sty) (c:/texlive/2023/texmf-dist/tex/latex/koma-script/scrsize12pt.clo) (c:/texlive/2023/texmf-dist/tex/latex/koma-script/typearea.sty
DIV calculation for typearea with good linewidth.
)))
! Emergency stop.
<*> .../emes_template-main/settings+/docclass.tex"
                                                  
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on docclass.log.
Latexmk: Sometimes, the -f option can be used to get latexmk
  to try to force complete processing.
  But normally, you will need to correct the file(s) that caused the
  error, and then rerun latexmk.
  In some cases, it is best to clean out generated files before rerunning
  latexmk after you've corrected the files.
Reverting Windows console CPs to (in,out) = (850,850)
Latexmk: Getting log file 'docclass.log'
Latexmk: Examining 'docclass.fls'
Latexmk: Examining 'docclass.log'
Latexmk: Errors, so I did not complete making targets
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'docclass.log' and/or above output for details

C:\texlive\2023\bin\windows\runscript.tlu:921: command failed with exit code 12:
perl.exe c:\texlive\2023\texmf-dist\scripts\latexmk\latexmk.pl -synctex=1 -interaction=nonstopmode -file-line-error -pdf "-outdir=c:/Users/PC/Downloads/emes_template-main/emes_template-main/settings+" "c:/Users/PC/Downloads/emes_template-main/emes_template-main/settings+/docclass"

```

**Comment by schlegan** [comment]
Alright, I think I see, whats going on: `Latexmk` does not find our configuration file `.latexmkrc`.

Could be because of the name, `.filename` is not really a windows thing, or because where your latex workshop extension is looking for the configuration file.

I'm gonna take a look and try to find that out.

**Comment by schlegan** [comment]
This is currently just a hunch, but could it be, that you have the wrong [root file](https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#the-root-file) set?

Our is the aptly named `main.tex`.

**Comment by schlegan** [comment]
Now we are getting somewhere!

As seen by
```
Rc files read:
  .latexmkrc
```
it now finds and reads our configuration file!

> I've prepended
> 
> ```
> % !TeX root = main.tex
> % !TeX program = lualatex
> ```
> 
> to the main.tex file.

Alright, bit weird place for you to define the root file. That should be done in your vsc project, not the latex code itself. You also should not need the line `% !TeX program = lualatex`, we already defined that in `.latexmkrc`, line 10.

> It looks like there is some error with LuaTeX: You must change your typesetting engine to, e.g., "xelatex" or "lualatex" instead of (fontspec) "latex" or "pdflatex".

As you can see in your longer error message, it is currently using  `pdflatex` instead of the wanted/defined `lualatex`. Do you have `lualatex` installed?

P. S.: May I propose a video meeting (via discord, zoom, whatever) to try and fix that in person? Should go a lot faster.

**Comment by Lukas1811** [comment]
Have a look at my [PR](https://github.com/imtekalex/emes_template/pull/7) I added a configuration file to have basic support for the VS Code "LaTeX Workshop" extension. The only issue I currently have is that the internal PDF viewer is not automatically updated when you build by saving another file than _main.tex_ (requires manual refresh of the PDF viewer).
It would require VS Code to watch the PDF file for changes and execute the _latex-workshop.refresh-viewer_ command on file change.

**Comment by schlegan** [comment]
Looks good to me.
